config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post '/lectures/import', to: 'lectures#create_lectures', as: 'create_lectures'
      get '/lectures/organize_event', to: 'lectures#organize_event', as: 'organize_event'
      delete '/api/v1/lectures/:id', to: 'lectures#destroy', as: 'destroy_lecture'
      put '/api/v1/lectures/:id', to: 'lectures#update', as: 'update_lecture'

      put 'lectures/update_multiple', to: 'lectures#update_multiple'
      delete 'lectures/destroy_multiple', to: 'lectures#destroy_multiple'
    end
  end

  resources :lectures do
    collection do
      post :import_csv
      delete :destroy_all
    end
  end

  root 'lectures#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  validates_uniqueness_of :title
end

app/controllers/api/v1/api_controller.rb
module Api::V1
	class ApiController < ApplicationController
	end
end

app/controllers/api/v1/lectures_controller.rb
class Api::V1::LecturesController < Api::V1::ApiController
  protect_from_forgery with: :null_session 
  # protect_from_forgery estou setando essa informação, apenas para facilitar o teste
  # caso fosse um ambiente real de prod isso nunca seria feito assim.

  def create_lectures
    data = JSON.parse(request.body.read)
    created_lectures = []
    errors = []
    data_formated = ExtractSchedulesService.new(data).extract

    data_formated.each do |entry|
      lecture = Lecture.new(title: entry[:title], duration: entry[:duration])
      if lecture.save
        created_lectures << lecture
      else
        errors << "Erro ao criar palestra: #{lecture.errors.full_messages.join(', ')}"
      end
    end

    response = {
      created_lectures: created_lectures,
      errors: errors
    }

    render json: response, status: :ok
  rescue JSON::ParserError
    render json: { error: 'JSON inválido' }, status: :unprocessable_entity
  end

  def organize_event
    @lectures = Lecture.all

    return [] if @lectures.empty?

    @tracks = OrganizeTracksService.new(@lectures).run

    respond_to do |format|
      format.json { render json: @tracks }
    end
  end

  def destroy_multiple
    lecture_ids = params[:lecture_ids]
    if lecture_ids.present?
      valid_ids = Lecture.where(id: lecture_ids).pluck(:id)

      if valid_ids.present?
        Lecture.where(id: valid_ids).destroy_all
        render json: { message: 'Palestras excluídas com sucesso' }, status: :ok
      else
        render json: { error: 'Nenhum ID de palestra válido fornecido' }, status: :unprocessable_entity
      end
    else
      render json: { error: 'Nenhum ID de palestra fornecido' }, status: :unprocessable_entity
    end
  end

  def update_multiple
    lecture_updates = params[:lecture_updates]

    if lecture_updates.present?
      lecture_updates.each do |update_params|
        lecture = Lecture.find(update_params[:id])
        lecture.update(update_params.slice(:title, :duration))
      end

      render json: { message: 'Palestras atualizadas com sucesso' }, status: :ok
    else
      render json: { error: 'Nenhum dado de atualização fornecido' }, status: :bad_request
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  require 'csv'
  before_action :set_lecture, only: %i[show edit update destroy]

  def index
    @lectures = Lecture.all
    @tracks = {}

    return [] if @lectures.empty?

    organized_tracks = OrganizeTracksService.new(@lectures).run

    if organized_tracks[:organize]
      organized_data = {}

      organized_tracks[:data].each do |item|
        track = item[:track]
        organized_data[track] ||= []
        organized_data[track] << item
      end

      @tracks = organized_data
    else
      @error = organized_tracks[:error]
    end
  end

  # GET /lectures/1 or /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  def import_csv
    uploaded_file = params[:file]

    if uploaded_file.nil?
      flash[:alert] = "Selecione um arquivo CSV para importar."
      redirect_to import_lectures_path
      return
    end

    if uploaded_file.content_type != 'text/csv'
      flash[:alert] = "Selecione um arquivo CSV válido."
      redirect_to import_lectures_path
      return
    end

    service = LectureImportService.new
    result = service.import(uploaded_file)

    if result[:success]
      flash[:notice] = "#{result[:created_count]} palestras criadas com sucesso!"
    else
      flash[:alert] = "Ocorreram erros durante a importação."
    end
    redirect_to lectures_path
  rescue StandardError => e
    flash[:alert] = "Ocorreu um erro durante a importação: #{e.message}"
  end

  # GET /lectures/1/edit
  def edit
  end

  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully created." }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_all
    Lecture.destroy_all
    redirect_to lectures_path, notice: 'Todas as palestras foram apagadas com sucesso.'
  end

  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully updated." }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url, notice: "Lecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_lecture
    @lecture = Lecture.find(params[:id])
  end

  def lecture_params
    params.require(:lecture).permit(:title, :duration)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiDePalestras</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lectures/_form.html.erb
<%= form_with(model: lecture) do |form| %>
  <% if lecture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% lecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/_lecture.html.erb
<div id="<%= dom_id lecture %>">
  <p>
    <strong>Title:</strong>
    <%= lecture.title %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= lecture.duration %>
  </p>

</div>

app/views/lectures/edit.html.erb
<h1 class="mt-4">Editing Lecture</h1>

<%= render "form", lecture: @lecture %>

<div class="mt-3">
  <%= link_to "Show this Lecture", @lecture, class: "btn btn-info" %> |
  <%= link_to "Back to Lectures", lectures_path, class: "btn btn-secondary" %>
</div>

app/views/lectures/index.html.erb
<div data-controller="lecture" class="container mt-4">
  
  <h1 class="text-center">Palestras no dia da Conferência</h1>

  <div class="d-flex justify-content-between">
    <%= form_tag({ action: :import_csv }, multipart: true) do %>
      <div class="form-group">
        <%= file_field_tag :file, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Importar CSV', class: 'btn btn-success' %>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= link_to "Adicionar Palestras", new_lecture_path, class: "btn btn-success" %>
    </div>
  </div>  

  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Horário</th>
        <th>Título</th>
        <th>Duração (minutos)</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @tracks.each do |track, items| %>
        <tr>
          <th class="bg-info" scope="row" colspan="3">Track <%= track %></th>
        </tr>
        <% items.each_with_index do |item, index| %>
          <tr class="<%= 'table-secondary' if index.even? %>">
            <td><%= item[:schedule] %></td>
            <td><%= item[:title] %></td>
            <% if item[:duration].present? %>
              <td><%= "#{item[:duration]} Min" %></td>
            <% end %>
            <% if item[:id].present? %>
              <td>
                <%= link_to "Show", lecture_path(id: item[:id]) %>
                <%= link_to "Edit", edit_lecture_path(id: item[:id]) %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="form-group">
    <div class="text-right">
      <%= button_to "Excluir Todas as Palestras", destroy_all_lectures_path, method: :delete, data: { confirm: 'Tem certeza que deseja apagar todas as palestras?' }, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/lectures/new.html.erb
<h1>Criar Palestras</h1>

<%= form_with model: @lecture, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title, 'Tema da Palestra' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :duration, 'Duração (minutos)' %>
    <%= form.number_field :duration, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.submit 'Salvar Palestra', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/lectures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lecture %>

<div>
  <%= link_to "Edit", edit_lecture_path(@lecture), class: "btn btn-primary" %> |
  <%= link_to "Back", lectures_path, class: "btn btn-secondary" %>

  <%= button_to "Destroy", @lecture, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>